#! /bin/bash

if [[ $# -ne 1 ]]
then
	echo "USAGE: $0 SET/RESET"
  echo "SET: Removes Buttons"
  echo "RESET: Brings back all buttons"
	exit 1
fi

if [[ $1 = "SET" ]]
then
	gsettings set org.gnome.desktop.wm.preferences button-layout :
else
	gsettings reset org.gnome.desktop.wm.preferences button-layout
fi
